name: Vivek Singh - Portfolio
description: A premium, interactive 3D developer portfolio built with React, TypeScript, and Three.js
homepage: https://vivekvsingh19.dev
topics:
  - portfolio
  - developer
  - react
  - typescript
  - three-js
  - 3d
  - vivekvsingh19
  - interactive-3d
  - framer-motion
  - tailwindcss
